# Generated by Django 5.1.3 on 2024-11-27 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Levels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True)),
                ('song_name', models.CharField(max_length=200)),
                ('song_author', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('level_author', models.CharField(max_length=100)),
                ('dl_link', models.CharField(max_length=250)),
                ('vd_link', models.CharField(max_length=250)),
            ],
        ),
    ]
